# Chapter 7: Array-Oriented Programming with NumPy

### 7.2 Creating arrays from existing data

In [2]:
import numpy as np

numbers = np.array([2, 3, 5, 7, 11])
print(numbers)

type(numbers)

[ 2  3  5  7 11]


numpy.ndarray

Multidimensional arguments

In [3]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

### 7.2 Self Check

In [7]:
numbers1 = np.array([item for item in range(2, 21, 2)])
print(numbers1)

[ 2  4  6  8 10 12 14 16 18 20]


In [9]:
numbers2 = np.array([[item for item in range(2, 11, 2)], [item for item in range(1, 10, 2)]])
print(numbers2)

[[ 2  4  6  8 10]
 [ 1  3  5  7  9]]


### 7.3 array attributes

In [13]:
import numpy as np

integers = np.array([[1, 2, 3], [4, 5, 6]])
print(integers)

floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])
print(floats)

[[1 2 3]
 [4 5 6]]
[0.  0.1 0.2 0.3 0.4]


**Determining an array's element type**

In [17]:
integers.dtype

dtype('int64')

In [18]:
floats.dtype

dtype('float64')

**Determing an array's dimensions**

In [19]:
integers.ndim

2

In [20]:
floats.ndim

1

In [21]:
integers.shape

(2, 3)

In [22]:
floats.shape

(5,)

**Determining an array's number of elements and element size**
- size: total number of elements
- itemsize: number of bytes required to store each element

In [23]:
integers.size

6

In [24]:
integers.itemsize

8

In [25]:
floats.size

5

In [26]:
floats.itemsize

8

**Iterating through a multidimensional array's elements**

In [29]:
for row in integers:
    for column in row:
        print(column, end=' ')
    print()

1 2 3 
4 5 6 


**You can iterate through a multidimensional array as if it were one-dimensional by using its flat attribute**

In [30]:
for i in integers.flat:
    print(i, end=' ')

1 2 3 4 5 6 

### 7.3 Self Check

In [32]:
print(numbers2.ndim)
print(numbers2.shape)

2
(2, 5)


### 7.4 Filling arrays with specific values

In [34]:
import numpy as np

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [38]:
np.ones((2, 4), dtype=float) #Specify the array's element type with the dtype argument

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
np.full((3, 5), 13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

### 7.5 Creating arrays from ranges

**Creating integer ranges with arrange**

In [40]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [41]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [43]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

**Creating floating-point ranges with linespace**: create evenly spaced floating-point ranges

In [52]:
np.linspace(0.0, 1.0, num=5)
# first, second numbers: starting and ending values (ending value is including in the array)
# last number: number of evenly spaced values to produce (the default value is 50)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [53]:
np.linspace(0.0, 1.0, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

**Reshaping an array**

In [55]:
np.arange(1, 21).reshape(4, 5) # chained method call

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

**Displaying large arrays**

In [56]:
np.arange(1, 100001).reshape(4, 25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [57]:
np.arange(1, 100001).reshape(100, 1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

### 7.5 Self Check

In [58]:
np.arange(2, 41, 2).reshape(4, 5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

### 7.6 Python Magic

- %timeit -n3 -r2
- %load: to read code into Ipython from a local file or URL
- %run: to execute a .py file from Ipython
- %precision: to change the default floating-point precision for ipython outputs
- %cd: to change directories without having to exit ipython first
- %edit to launch an external editor
- %history to view a list of all snippets and commands you've executed in the current ipython session

### 7.7 array operators

**Arithmetic operations with arrays and individual numeric values**: each returns a new array containing the result

In [4]:
import numpy as np
numbers = np.arange(1, 6)
numbers * 2

array([ 2,  4,  6,  8, 10])

In [5]:
numbers ** 3

array([  1,   8,  27,  64, 125])

In [6]:
numbers # numbers is unchanged by the arithmetic operations

array([1, 2, 3, 4, 5])

**Augmented assignments modify every element in the left operand**

In [7]:
numbers += 10
print(numbers)

[11 12 13 14 15]


**Broadcasting**: When one operand is a single value, called a scalar, NumPy performs the element-wise calculations as if the scalar were an array of the same shape as the other operand, but with the scalar value in all its elements.

In [8]:
numbers * [2, 2, 2, 2, 2]

array([22, 24, 26, 28, 30])

In [9]:
numbers * 2

array([22, 24, 26, 28, 30])

**Arithmetic operations between arrays**: you may perform arithmetic operations and augmented assignments between arrays of the same shape

In [12]:
numbers2 = np.linspace(1.1, 5.5, 5)
print(numbers2)

numbers * numbers2

[1.1 2.2 3.3 4.4 5.5]


array([12.1, 26.4, 42.9, 61.6, 82.5])

**Comparing arrays**: comparisons are performed element-wise

In [13]:
numbers

array([11, 12, 13, 14, 15])

In [14]:
numbers >= 13

array([False, False,  True,  True,  True])

In [15]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [16]:
numbers2 < numbers

array([ True,  True,  True,  True,  True])

In [17]:
numbers == numbers2

array([False, False, False, False, False])

In [18]:
numbers == numbers

array([ True,  True,  True,  True,  True])

### 7.7 Self Check